services:
  wordpress:
    depends_on:
      - wordpress_db
    container_name: WordPress
    hostname: wordpress
    image: wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: ${WordPress_db_user}
      WORDPRESS_DB_PASSWORD: ${WordPress_Pass}
      WORDPRESS_DB_NAME: WordPress_db
    volumes:
      - ./WordPress:/var/www/html
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  wordpress_db:
    container_name: wordpress_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: WordPress_db
      MYSQL_USER: ${WordPress_db_user}
      MYSQL_PASSWORD: ${WordPress_Pass}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./WordPress_database:/var/lib/mysql
    networks:
      - my_network

  wordpress_redis:
    image: redis
    container_name: wordpress_redis
    hostname: wordpress_redis
    restart: always
    expose:
      - 6379
    volumes:
      - ./WordPress_redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  my_network:
    name: my_network
    driver: bridge
